sudo: required
dist: trusty
language: node_js
node_js:
- '4'
- '7'
before_install:
- curl https://install.meteor.com/ | sh
- export PATH=$HOME/.meteor:$PATH
- wget -qO- https://toolbelt.heroku.com/install-ubuntu.sh | sh
- heroku
- meteor add dispatch:mocha
script:
- meteor test --once --driver-package dispatch:mocha
- TEST_BROWSER_DRIVER=phantomjs meteor test --once --full-app --driver-package dispatch:mocha

deploy:
  provider: heroku
  api_key: {HEROKU_API_KEY}
  app: pvemeteordemo
