sudo: false
language: node_js
node_js:
  - "0.10"
  - "4"
  - latest
  
before_install: 
  - curl https://install.meteor.com/ | sh
  - export PATH=$HOME/.meteor:$PATH
  - meteor add dispatch:mocha #practicalmeteor is the browser version, not the ci version
